CC=g++

test1:test1.cpp
	$(CC) test1.cpp -o test1
test2:test2.cpp
	$(CC) test2.cpp -o test2
testsignal:testsignal.c 
	$(CC) testsignal.c ../src/paignal.cpp -I../include/  -o testsignal

clean:
	rm test1 test2